# archivo: install_apache.yml
- hosts: web_servers
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
    

     - name: Habilitar y iniciar Apache
      service:
        name: apache2
        state: started
        enabled: true